### ISSUE TITLE
Record Test Results fails on windows

### ISSUE THREAD

**Issue by GunnyDev** [launchableinc/cli#187]
### Context
Testing Launchable on a Monolithic .Net 4.7.2 Application that can only be build using windows agents.

### Current Behaviour
`launchable record tests` command fails on windows environment returning the following error:

`Traceback (most recent call last):
  File "c:\users\kevin.gunn\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\kevin.gunn\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\Scripts\launchable.exe\__main__.py", line 7, in <module>
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\launchable\commands\record\tests.py", line 60, in tests
    session_id = find_or_create_session(context, session, build_name)
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\launchable\commands\helper.py", line 23, in find_or_create_session
    session_id = read_session(build_name)
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\launchable\utils\session.py", line 34, in read_session
    f = _session_file_path(build_name)
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\launchable\utils\session.py", line 19, in _session_file_path
    return _session_file_dir() / (hashlib.sha1("{}:{}".format(build_name, _get_session_id()).encode()).hexdigest() + ".txt")
  File "C:\Users\kevin.gunn\AppData\Roaming\Python\Python38\site-packages\launchable\utils\session.py", line 23, in _get_session_id
    id = os.getsid(os.getpid())
AttributeError: module 'os' has no attribute 'getsid'`

Expected Behaviour
The `launchable record tests` command to work successfully on a windows environment.

**Comment by ninjinkun** [comment]
@GunnyDev Thanks for reporting. Finally, we released a Windows-compatible version! Please try the latest one.

**Comment by GunnyDev** [comment]
@ninjinkun Awesome, thanks! I will give it a go.
