### ISSUE TITLE
Launchable is killing test runs

### ISSUE THREAD

**Issue by brianjmurrell** [launchableinc/cli#441]
Due to errors that `launchable` runs into, it ends up exiting with a non-zero status and killing a test run, despite assurances that adding Launchable to one's testing processes will **not** make one's test process more fragile.  Having Launchable kill a test run that would have otherwise run fine is adding fragility to our test runs.  I have complained about this multiple times in the past but this just seems to go on and on.  I cannot convince my team to continue to use Launchable if it's going to make our CI processes more fragile.

Here's the latest:

```
[2022-08-11T05:29:46.918Z] + launchable record build --name jenkins-daos-stack-daos-ci-daos-do-packer-ofed-images-PR-2-release-2.0-20 --source src=.
[2022-08-11T05:29:47.854Z] Exception in thread "main" java.lang.IllegalArgumentException: One of setGitDir or setWorkTree must be called.
[2022-08-11T05:29:47.854Z] 	at org.eclipse.jgit.lib.BaseRepositoryBuilder.requireGitDirOrWorkTree(BaseRepositoryBuilder.java:636)
[2022-08-11T05:29:47.854Z] 	at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:600)
[2022-08-11T05:29:47.854Z] 	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:625)
[2022-08-11T05:29:47.854Z] 	at com.launchableinc.ingest.commits.CommitIngester.run(CommitIngester.java:133)
[2022-08-11T05:29:47.854Z] 	at com.launchableinc.ingest.commits.CommitIngester.main(CommitIngester.java:74)
[2022-08-11T05:29:47.854Z] Can't get commit history from `/data/jenkins/jenkins-1/ci_vm_wolf-106vm1-9/workspace/ker-ofed-images-PR-2-release-2.0`. Do you run command root of git-controlled directory? If not, please set a directory use by --source option.
f
[2022-08-11T05:29:47.854Z] fatal: Not a git repository (or any parent up to mount point /data)
[2022-08-11T05:29:47.854Z] Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[2022-08-11T05:29:47.854Z] Can't get commit hash. Do you run command under git-controlled directory? If not, please set a directory use by --source option.
[2022-08-11T05:29:47.854Z] Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
[2022-08-11T05:29:47.854Z] Command '['java', '-jar', '/localhome/lcl_builder/.local/lib/python3.6/site-packages/launchable/jar/exe_deploy.jar', 'ingest:commit', '-endpoint', 'https://api.mercury.launchableinc.com/intake/', '-max-days', '30', '-scrub-pii', '/data/jenkins/jenkins-1/ci_vm_wolf-106vm1-9/workspace/ker-ofed-images-PR-2-release-2.0']' returned non-zero exit status 1.
```

**Comment by Konboi** [comment]
Thank you for reporting the comment.

Yes, the cli shouldn't suspend the user pipeline especially cause of Launchable side problems.
However, the cli needs to notify the user when the user misses or fails to set up the cli. In short, the cli shouldn’t ignore all errors.

In this case, it seems to be that you set an incorrect directory.
If the cli couldn’t collect commit history, Launchable won’t predict the test selection. So, the cli needs to inform the users of this issue as an error.

Or, this pipeline has usually worked well, but it was sometimes stopped cause of the cli error, right?
If so sorry and we need to know the situation more deeply.

**Comment by awilkes** [comment]
Right, it's a balance. Our priority is that the CLI should not return an error when the service is legitimately down. I recall you've been bitten by this, and I recognize and apologize that we've not done a great job here. I think we still have some improvements to make there, and if you're still seeing that, please let us know.

However, for the CLI to _never_ raise an error, even in the case of misconfiguration, would present its own challenges, both for us and our customers.

This _specific_ error doesn't look like a service issue. It looks like a configuration issue OR a CLI bug where a previously working configuration is on longer working (which would obviously be very bad!)

Do you know if the `launchable` invocation has changed or anything about the repository has changed? Thanks.
