### ISSUE TITLE
Trying to subset yields UnboundLocalError: local variable 'case' referenced before assignment

### ISSUE THREAD

**Issue by brianjmurrell** [launchableinc/cli#450]
When I try to subset with:

```
$ launchable subset --session builds/jenkins-daos-stack-daos-PR-10182-5/test_sessions/1364476 --target 100% pytest < tests.txt 
Traceback (most recent call last):
  File "/home/brian/.local/bin/launchable", line 8, in <module>
    sys.exit(main())
  File "/home/brian/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/brian/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/brian/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brian/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brian/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brian/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/brian/.local/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/brian/.local/lib/python3.10/site-packages/launchable/test_runners/pytest.py", line 60, in subset
    client.run()
  File "/home/brian/.local/lib/python3.10/site-packages/launchable/commands/subset.py", line 347, in run
    self.output_handler(_output, _rests)
  File "/home/brian/.local/lib/python3.10/site-packages/launchable/commands/subset.py", line 181, in _default_output_handler
    self.print(output)
  File "/home/brian/.local/lib/python3.10/site-packages/launchable/commands/test_path_writer.py", line 49, in print
    click.echo(self.separator.join(self.formatter(t)
  File "/home/brian/.local/lib/python3.10/site-packages/launchable/commands/test_path_writer.py", line 49, in <genexpr>
    click.echo(self.separator.join(self.formatter(t)
  File "/home/brian/.local/lib/python3.10/site-packages/launchable/test_runners/pytest.py", line 109, in _pytest_formatter
    return "{}::{}".format(file, case)
UnboundLocalError: local variable 'case' referenced before assignment
```

where `tests.txt` contains:

```
./pool/destroy.py
./pool/create_all_vm.py
./control/ms_resilience.py
./mpiio/llnl_mpi4py.py
./control/ms_failover.py
./control/dmg_server_set_logmasks.py
./pool/evict.py
./control/dmg_telemetry_basic.py
./daos_test/dfuse.py
./datamover/posix_preserve_props.py
./datamover/serial_small.py
./container/simple_create_delete.py
./network/cart_self_test.py
```

**Comment by Konboi** [comment]
We'll check it

**Comment by Konboi** [comment]
I could replay this error, sorry. We'll fix it ASAP

**Comment by takanabe** [comment]
@brianjmurrell Thank you for reaching out us.

In short, your `tests.txx` contains  the invalid test cases for `launchable` command with `pytest.

Using `launchable` commands with `pytest` expects to receive the **testcases** rather than **files** and you can create the correct file with the command below.

```
$ pytest --collect-only -q . > tests.txt
$ tests.txt
tests/funcs3_test.py::test_func4
tests/funcs3_test.py::test_func5
tests/test_func5.py::test_func5[3+5-8]
tests/test_func5.py::test_func5[2+4-6]
tests/test_func5.py::test_func5[6*9-42]
tests/test_func5.py::test_foo[2-0]
tests/test_func5.py::test_foo[2-1]
tests/test_func5.py::test_foo[3-0]
tests/test_func5.py::test_foo[3-1]
tests/test_funcs1.py::test_func1
tests/test_funcs1.py::test_func2
tests/test_funcs2.py::test_func3
tests/test_funcs2.py::test_func4
tests/test_mod.py::TestClass::test__can_print_aaa
tests/fooo/test_func4.py::test_func6

15 tests collected in 0.01s
```

You can pass this `tests.txt` as follows:

```
$ launchable subset --session builds/testbuild-taka/test_sessions/6 --target 100% pytest < tests.txt

tests/test_funcs1.py::test_func2
tests/test_func5.py::test_foo[3-0]
tests/fooo/test_func4.py::test_func6
tests/test_funcs2.py::test_func4
tests/test_mod.py::TestClass::test__can_print_aaa
tests/test_funcs2.py::test_func3
tests/test_func5.py::test_func5[3+5-8]
tests/test_func5.py::test_func5[2+4-6]
tests/test_funcs1.py::test_func1
tests/test_func5.py::test_foo[2-1]
tests/funcs3_test.py::test_func4
tests/test_func5.py::test_foo[2-0]
tests/funcs3_test.py::test_func5
tests/test_func5.py::test_foo[3-1]
tests/test_func5.py::test_func5[6*9-42]
Your model is currently in training
Launchable created subset 9 for build testbuild-taka (test session 6) in workspace launchableinc/mothership

|           |   Candidates |   Estimated duration (%) |   Estimated duration (min) |
|-----------|--------------|--------------------------|----------------------------|
| Subset    |           15 |                      100 |                    0.00025 |
| Remainder |            0 |                        0 |                    0       |
|           |              |                          |                            |
| Total     |           15 |                      100 |                    0.00025 |

Run `launchable inspect subset --subset-id 9` to view full subset details
```

I'm not sure how you generate the list in your `tests.txt` but if you follow the above procedures, I believe you can execute the subset command. The details of the above steps are documented our CLI manual page and I'd like you to check [the page](https://docs.launchableinc.com/resources/integrations/pytest#subsetting-your-test-runs). Hopefully, this can resolve the error.

**Comment by brianjmurrell** [comment]
Can I query a session to see the list of tests that it has recorded for a test run.

In all honesty, I am not using _pytest_ but a test framework modelled on it called [Avocado](https://avocado-framework.readthedocs.io/en/latest/) and trying to figure out how I can get what launchable recorded from it's JUnit file into a set of tests that I can call.

But in order to do that, I need to sew what Launchable thinks are the tests run for a given session and then see how I can turn that into a command that runs the respective Avocado tests.

**Comment by awilkes** [comment]
Ah! Makes sense. Take a look at [`launchable inspect tests`](https://docs.launchableinc.com/resources/cli-reference#inspect-tests).
