### ISSUE TITLE
Traceback when running `launchable record tests maven --help`

### ISSUE THREAD

**Issue by basil** [launchableinc/cli#554]
### Steps to reproduce

Run `launchable record tests maven --help`.

### Expected results

Detailed usage information, no traceback, and an exit status of 0.

### Actual results

No detailed usage information, a traceback, and an exit status of 0 (!) despite the traceback.

```
$ launchable record tests maven --help
Traceback (most recent call last):
  File "lib/python3.10/site-packages/launchable/commands/record/tests.py", line 200, in tests
    session_id = str(find_or_create_session(
  File "lib/python3.10/site-packages/launchable/commands/helper.py", line 54, in find_or_create_session
    raise click.UsageError(
click.exceptions.UsageError: No saved build name found.
To fix this, run `launchable record build`.
If you already ran this command on a different machine, use the --session option. See https://docs.launchableinc.com/sending-data-to-launchable/managing-complex-test-session-layouts
Usage: launchable record tests maven [OPTIONS] SOURCE_ROOTS...

Options:
  --help  Show this message and exit.
$ echo $?
0
```

**Comment by Konboi** [comment]
Thank you for your report, we'll check it
